name: Publish

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install pelican
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install --user pelican markdown
    - name: Build content
      run: python -m pelican content -o docs
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "[action] Automated deployment"
    - name: Push commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_SECRET_NAME: ${{ secrets.MY_SECRET_NAME }}
      run: |
        echo "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
