name: Publish

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_SECRET_NAME: ${{ secrets.MY_SECRET_NAME }} 
      run: echo ${MY_SECRET_NAME} ${GITHUB_TOKEN}
    - name: Pelican build
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install --user pelican
        python -m pelican content -o docs
    - name: Commit and push files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "[action] Automated deployment"
        remote_repo="https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:gh-pages --follow-tags
